### ISSUE TITLE
[Question]: Connecting to 2602B

### ISSUE THREAD

**Issue by SwaggerNiels** [tektronix/tsp-toolkit#33] opened 2024-07-15 13:59 UTC
### Pre-check

- [x] I have searched the existing issues and discussions to make sure my problem has not already been addressed.
- [X] I have looked at the "Known Issues" Section of the marketplace page of all TSP Toolkit extensions.

### Search Terms

"connection issue" 

### TSP Toolkit Version

0.16.1

### TSP Toolkit Develop Version

None

### Steps to Reproduce

  using version [0.16.1](https://github.com/tektronix/tsp-toolkit/releases/tag/v0.16.1)

1. Set config
``` json
{
    "$schema": "./tspSchema.json",
    "nodes":{
    },
    "self": "2602B"
}
```
  2. Open Command Pallette and enter "TSP: Open Terminal"
  3. Select "New Connection"
  4. Type in IP address for 2602B
  5. Type in name "keithley1"

### Expected Behavior

Connecting to device

### Actual Behavior

popup message "Unable to connect to device"

**Comment by esarver** [comment] 2024-07-17 12:54
@SwaggerNiels Thanks for the issue report! We always appreciate the feedback! We will look into this.

A note: the config file has no bearing on whether an instrument connects or not. Right now it only effects the language services (the autocomplete, syntax error detection, documentation, etc.). I appreciate you including all possible relevant information, though. That helps immensely with the debugging process. 

That being said, we should be able to connect to a 2602B. I'll look around to find one to test with and let you know what we find. In the mean time, if there is any other information you can think of, feel free to add additional comments on this issue.

**Comment by esarver** [comment] 2024-08-23 19:13
@SwaggerNiels Several people tested this internally and all users were able to connect to their 2602 over LAN. Since we aren't able to reproduce I will close this ticket. If you still experience the problem on updated versions of TSP Toolkit, feel free to reopen this and provide us more information like firmware version of the instrument and the logs (if you let me know your OS [windows or linux], I can get you the file location of those logs).

**Closed by esarver** 2024-08-23 19:13 UTC
Labels: bug, triage
